language: node_js
node_js:
- '4.0'
- '4'
- '6.0'
- '6'
- '8.0'
- '8'
- '9'
sudo: false
script:
- npm run lint
- npm test -- -- -- --bail --timeout 5000 --reporter dot
after_success:
- npm run coveralls
notifications:
  email: false
  slack:
    secure: jI3gt+t9s6NRCuMnEfQKqNziWpTVxKMAv2sXIukDzNgBzTl70oZcn4gGOoD+JWfPBDZV/3UFrKh3kEBKfIcfMbFaudfxPZLxeXwTtzvOxq1AfdH8mAZwqwSCtDu+1g6KfHtbyEHfJvJZGWKuGDgJUKq5rrkeU8v5rCALFZQbDKo=
branches:
  only:
  - master
  - develop
